version: '3.2'

services:

  proxy:
    image: nginx
    volumes:
     # - ../nginx/static.conf:/etc/nginx/conf.d/mysite.template
     - ../nginx/static.conf:/etc/nginx/conf.d/default.conf
     - /home/mrurenko/projects/compare-frontends/mr-angular/dist:/usr/share/nginx/html
    ports:
    - 80:80
    environment:
    - NGINX_PORT=80
    - BACKEND_HOST="localhost:3000"
    network_mode: "host"
    # - NGINX_HOST=foobar.com
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: postgres
    volumes:
      - type: volume
        source: db-data-express
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data-express:

# networks:
#   host-net:
#     external:
#       name: host
